### ISSUE TITLE
Re-Read Programming Phoenix Book for v.1.4

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/rumbl#1]
With the recent release of the Programming Phoenix 1.4 Book (2018-10-19)
see: https://github.com/dwyl/learn-phoenix-framework#book
I feel that it would be a _good_ use of my time to re-read it and follow all the examples
to ensure that my knowledge is up-to-date for my upcoming Phoenix-based web app projects.

If I sit down and focus, I estimate that it will probably take me 4 days (_two uninterrupted weekends..._)
to read the 269 pages and write the example code.

Better get cracking!

**Comment by nelsonic** [comment]
Beta 9 released July 24 ... anyone `else` feel the _irony_ of a _typo_ in the release note? 🙄 
![image](https://user-images.githubusercontent.com/194400/62610033-bb95c400-b8fa-11e9-8bac-e5e433cf1a8b.png)

inexing indeed ...

**Comment by nelsonic** [comment]
http://localhost:4000/watch/6-totes-amaze-video
![image](https://user-images.githubusercontent.com/194400/62612517-6a3c0380-b8ff-11e9-85a2-f8efd8f8b9cc.png)

**Comment by nelsonic** [comment]
p.204: "_Each channel module has three ways to receive events. You’ll learn more about these callback functions in detail soon. For now, know that `handle_in` receives **direct channel events**, `handle_out` intercepts **broadcast** events, and `handle_info` receives **OTP messages**_".

**Comment by nelsonic** [comment]
p.232 Introspecting Applications with Observer
```
$ iex -S mix
iex> :observer.start()
```
![image](https://user-images.githubusercontent.com/194400/62732294-e88dc800-ba1b-11e9-8043-bc141bd816d0.png)
![image](https://user-images.githubusercontent.com/194400/62733671-03ae0700-ba1f-11e9-87e0-192f608aba2c.png)
![image](https://user-images.githubusercontent.com/194400/62732373-0eb36800-ba1c-11e9-9727-de0d2a413184.png)


This is a dream for DevOps and debugging. 😍

**Comment by nelsonic** [comment]
When you see the following error:
```
Module not found: Error: Can't resolve 'phoenix' in 'code/rumbl_umbrella/apps/rumbl_web/assets/js'
Module not found: Error: Can't resolve 'phoenix_html' in 'code/rumbl_umbrella/apps/rumbl_web/assets/js'
```

Try: https://elixirforum.com/t/phoenix-phoenix-html-npm-error-for-umbrella-project/17575/2
i.e. _manually_ create the symlinks with:


`.then` if you see this error (_repeatedly_):
```
[error] GenServer #PID<0.461.0> terminating
** (ArgumentError) argument error
    (stdlib) :ets.lookup(RumblWeb.Presence, :pool_size)
    (phoenix_pubsub) lib/phoenix/tracker.ex:279: Phoenix.Tracker.pool_size/1
    (phoenix_pubsub) lib/phoenix/tracker.ex:215: Phoenix.Tracker.list/2
    (phoenix) lib/phoenix/presence.ex:355: Phoenix.Presence.list/2
    (rumbl_web) lib/rumbl_web/channels/video_channel.ex:23: RumblWeb.VideoChannel.handle_info/2
    (phoenix) lib/phoenix/channel/server.ex:305: Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :after_join
State: %Phoenix.Socket{assigns: %{user_id: 2, video_id: 6}, channel: RumblWeb.VideoChannel, channel_pid: #PID<0.461.0>, endpoint: RumblWeb.Endpoint, handler: RumblWeb.UserSocket, id: "users_socket:2", join_ref: "157", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: RumblWeb.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "videos:6", transport: :websocket, transport_pid: #PID<0.457.0>}
```

Go hunting through the Errata in: https://pragprog.com/titles/phoenix14/errata 🙄 
I had to make a couple of changes which were a good test of my Umbrella Knowledge.

_First_ in the file `apps/rumbl_web/lib/rumbl_web/application.ex`, add `RumblWeb.Presence` to the list of supervised child processes, e.g:
```elixir
    children = [
      RumblWeb.Endpoint,
      RumblWeb.Presence
    ]
```

Then in the `apps/rumbl_web/lib/rumbl_web/channels/presence.ex` file, change:
```elixir
  use Phoenix.Presence,
    otp_app: :rumbl,
    pubsub_server: Rumbl.PubSub
```

to:
```elixir
  use Phoenix.Presence,
    otp_app: :rumbl_web,
    pubsub_server: RumblWeb.PubSub
```

_Now_ it works. ✅

**Comment by nelsonic** [comment]
When you see the following error:
```
Module not found: Error: Can't resolve 'phoenix' in 'code/rumbl_umbrella/apps/rumbl_web/assets/js'
Module not found: Error: Can't resolve 'phoenix_html' in 'code/rumbl_umbrella/apps/rumbl_web/assets/js'
```

Try: https://elixirforum.com/t/phoenix-phoenix-html-npm-error-for-umbrella-project/17575/2
i.e. _manually_ create the symlinks with:


`.then` if you see this error (_repeatedly_):
```
[error] GenServer #PID<0.461.0> terminating
** (ArgumentError) argument error
    (stdlib) :ets.lookup(RumblWeb.Presence, :pool_size)
    (phoenix_pubsub) lib/phoenix/tracker.ex:279: Phoenix.Tracker.pool_size/1
    (phoenix_pubsub) lib/phoenix/tracker.ex:215: Phoenix.Tracker.list/2
    (phoenix) lib/phoenix/presence.ex:355: Phoenix.Presence.list/2
    (rumbl_web) lib/rumbl_web/channels/video_channel.ex:23: RumblWeb.VideoChannel.handle_info/2
    (phoenix) lib/phoenix/channel/server.ex:305: Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :after_join
State: %Phoenix.Socket{assigns: %{user_id: 2, video_id: 6}, channel: RumblWeb.VideoChannel, channel_pid: #PID<0.461.0>, endpoint: RumblWeb.Endpoint, handler: RumblWeb.UserSocket, id: "users_socket:2", join_ref: "157", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: RumblWeb.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "videos:6", transport: :websocket, transport_pid: #PID<0.457.0>}
```

Go hunting through the Errata in: https://pragprog.com/titles/phoenix14/errata 🙄 
I had to make a couple of changes which were a good test of my Umbrella Knowledge.

_First_ in the file `apps/rumbl_web/lib/rumbl_web/application.ex`, add `RumblWeb.Presence` to the list of supervised child processes, e.g:
```elixir
    children = [
      RumblWeb.Endpoint,
      RumblWeb.Presence
    ]
```

Then in the `apps/rumbl_web/lib/rumbl_web/channels/presence.ex` file, change:
```elixir
  use Phoenix.Presence,
    otp_app: :rumbl,
    pubsub_server: Rumbl.PubSub
```

to:
```elixir
  use Phoenix.Presence,
    otp_app: :rumbl_web,
    pubsub_server: RumblWeb.PubSub
```

_Now_ it works. ✅

**Comment by nelsonic** [comment]
On p.265 getting the following error:
```
** (ArgumentError) argument error
    (stdlib) :ets.insert(InfoSys.Cache_cache, {"one plus one?", "two"})
    (info_sys) lib/info_sys/cache.ex:7: InfoSys.Cache.put/2
```

I tried following https://elixirschool.com/en/lessons/specifics/ets/#inserting-data
and get the _same_ error:

![image](https://user-images.githubusercontent.com/194400/62825539-6d581d80-bba5-11e9-9684-7d341dd46cbb.png)

After a _lot_ of retracing of steps, I figured out that I _failed_ to follow the instruction on p.261 regarding putting `InfoSys.Cache` in the children (supervision tree) in application.ex 🙄

**Comment by nelsonic** [comment]
```
** (ArgumentError) could not fetch application environment :wolfram for application :rumbl because configuration :wolfram was not set
```
After reading the errata for the book https://pragprog.com/titles/phoenix14/errata
Found that @samcdavid had spotted and reported the issue:
![image](https://user-images.githubusercontent.com/194400/62826515-ef9c0e00-bbb4-11e9-98f2-c5a77152b8db.png)

opened: `apps/info_sys/lib/info_sys/wolfram.ex` and changed the _last_ line:

```elixir
  defp id, do: Application.fetch_env!(:rumbl, :wolfram)[:app_id]
```
To:
```elixir
defp id, do: Application.fetch_env!(:info_sys, :wolfram)[:app_id]
```

**Comment by nelsonic** [comment]
At the end of Chapter 12 (OTP) we have http://localhost:4000/watch/7
![image](https://user-images.githubusercontent.com/194400/62833307-a25f8100-bc34-11e9-9284-e39f9cff6f3e.png)

Wolfram alpha is inserting useful info in the annotations thread. 🎉

**Comment by nelsonic** [comment]
Had to submit another errata:  https://pragprog.com/titles/phoenix14/errata `#85673`
Sadly it is preventing me from finishing Chapter 13. 😞 
_Really_ hope they answer/fix it. 
Meanwhile I'm going to finish reading chapter 14 "What's Next?" which is unrelated to Rumbl.

**Comment by nelsonic** [comment]
Finished reading the Programming Phoenix 1.4 Book.
Felt that the last chapter was a bit of a cop-out. 
It _briefly_ covers LiveView (_but only basic demos no full app or useful extension to "Rumbl"_)
and mentions Telemetry but says that the API will change.
Touches upon Phoenix Channels 2.0 which is still in development ...
I would _much_ rather they pointed to where to go _next_ than finish with "Good Luck". 🙄 

Overall I would recommend the book. 👍 
But I feel they (_or someone `else`_) can still do _much_ better. 💭
